/**
 ******************************************************************************
 * @file    main.c
 * @brief   Actuator Node (Board B) entry point.
 *
 * CAN frame layout (see security_config.h / can_security.h for the
 * authoritative definitions, PRD §2):
 *   ACC data frame, ID 0x100, DLC 8:
 *     byte0 command | byte1 distance_cm | byte2 counter | byte3 crc8
 *     bytes4-7 mac[4] (truncated AES-128-CMAC over bytes 0-3)
 *   CRC8/SMBUS (poly 0x07, init 0xFF) over bytes 0-2 is a corruption filter
 *   ONLY -- it provides no protection against a deliberate attacker.
 *   Authenticity comes from the CMAC; freshness from the rolling counter
 *   (§2.5). A frame is only acted upon once ALL THREE checks pass.
 *
 * Fail-safe policy (PRD §3.5): if no frame has been validated in the last
 * ACC_LINK_TIMEOUT_MS (500 ms) -- whether because the bus is down, or
 * because frames are consistently failing CRC/MAC/freshness -- the motor
 * is forced to and held at 0% duty by SafetyMonitorTask, regardless of
 * whatever command was last validated. This is enforced independently of
 * MotorControlTask's normal ramp logic.
 *
 * NOTE: This file shows only the USER CODE insertions needed on top of a
 * standard CubeMX-generated main.c for this .ioc configuration. The
 * MX_GPIO_Init / MX_CAN1_Init / MX_TIM3_Init / MX_I2C1_Init / MX_IWDG_Init
 * calls in the generated SystemClock_Config()/init sequence are untouched
 * -- only the marked USER CODE blocks below need populating.
 ******************************************************************************
 */
/* USER CODE BEGIN Header */
/* (See file header above for the CAN frame layout / fail-safe summary.) */
/* USER CODE END Header */

#include "main.h"
#include "FreeRTOS.h"
#include "task.h"

/* USER CODE BEGIN Includes */
#include "can_driver.h"
#include "motor_driver.h"
#include "app_tasks.h"
/* USER CODE END Includes */

/* Peripheral handles generated by CubeMX in can.c / tim.c / i2c.c / iwdg.c */
extern CAN_HandleTypeDef  hcan1;
extern TIM_HandleTypeDef  htim3;
extern I2C_HandleTypeDef  hi2c1;
extern IWDG_HandleTypeDef hiwdg;

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
/* MX_CAN1_Init / MX_TIM3_Init / MX_I2C1_Init / MX_IWDG_Init declared in
 * their respective CubeMX-generated can.h / tim.h / i2c.h / iwdg.h */

int main(void)
{
    HAL_Init();
    SystemClock_Config(); /* CubeMX default: HSI 16 MHz, no PLL -- untouched */

    MX_GPIO_Init();
    MX_CAN1_Init();
    MX_TIM3_Init();
    MX_I2C1_Init();
    MX_IWDG_Init();

    /* USER CODE BEGIN 2 */
    if (ACC_CanDriver_Init(&hcan1) != HAL_OK)
    {
        Error_Handler();
    }
    if (ACC_Motor_Init(&htim3) != HAL_OK)
    {
        Error_Handler();
    }

    /* Creates all queues, the display mailbox, and all six application
     * tasks (PRD §3.4). Must run before the scheduler starts. */
    ACC_Tasks_Init();
    /* USER CODE END 2 */

    /* Start FreeRTOS scheduler (from your existing Middleware/FreeRTOS +
     * SEGGER SystemView setup -- not CubeMX's FreeRTOS wizard). */
    vTaskStartScheduler();

    /* USER CODE BEGIN WHILE */
    /* Never reached: vTaskStartScheduler() only returns on failure
     * (e.g. insufficient heap for the idle/timer tasks). */
    while (1)
    {
    }
    /* USER CODE END WHILE */
}

/* USER CODE BEGIN 4 */
/**
 * @brief HAL error handler. Reaching this means a peripheral init call
 *        above failed -- with no scheduler running yet, all we can safely
 *        do is stop and flash the status LED to signal bring-up failure.
 */
void Error_Handler(void)
{
    __disable_irq();
    for (;;)
    {
        HAL_GPIO_TogglePin(ACC_STATUS_LED_GPIO_Port, ACC_STATUS_LED_Pin);
        for (volatile uint32_t i = 0; i < 500000U; i++) { }
    }
}
/* USER CODE END 4 */
